# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: lihuan's Blog  #网站标题
subtitle: 前端狗一只... #副标题
description: 个人博客
author: 李欢 #作者
language: zh-Hans #简体中文
email: yd_lihuan@qq.com
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # 新建博文（帖子）的默认名称
default_layout: post #默认布局模板是post，而不是draft和page
titlecase: false #是否将标题转换成标题形式（首字母大写）
external_link: true #在新标签页面中打开网页
filename_case: 0
render_drafts: false
post_asset_folder: true #启动 Asset 文件夹
relative_link: false #把链接改为与根目录的相对位址
future: true
highlight: #代码块的设置
  enable: true
  line_number: true  # 显示行号
  auto_detect: true # 自动检测语言
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cyanstyle
stylus:
  compress: true #自适应布局

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:Fanlee/Fanlee.github.io.git
  branch: master

# title 外部链接
links_title: Links
links:
  MacTalk: http://macshuo.com/
  title: http://example.com/

# 侧边社交链接
social:
  GitHub: https://github.com/Fanlee
  微博: http://weibo.com/2784226692/profile?topnav=1&wvr=6
  
# Social Icons
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  微博: weibo
  
#打赏功能配置示例
#reward_comment: 坚持原创技术分享，您的支持将鼓励我继续创作！
#wechatpay: /path/to/wechat-reward-image
#alipay: /path/to/alipay-reward-image

#站点建立时间
since: 2017

# Wechat Subscriber
wechat_subscriber:
  enabled: true
  qcode: /uploads/weixin.png
  description: 欢迎您扫一扫上面的微信添加我
  
#搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
